language: android

before_install:
- nvm install 7
- node --version
- cd EKSY/

install:
- npm install

android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-19

script:
- npm test

after_success:
- npm run coverageToCoveralls
- 'if [ "$TRAVIS_BRANCH" == "master" ]; then
    cd android && ./gradlew assembleRelease
    code-push-travis -d Production --platform ["android"] --targetBinary `cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]'`
  fi'
