language: android

before_install:
- nvm install 7
- node --version
- cd EKSY/

install:
- npm install
- npm install -g code-push-cli

android:
  components:
  - build-tools-23.0.1
  - build-tools-25.0.3
  - android-23
  - android-25
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-19

script:
- npm test

after_success:
- npm run coverageToCoveralls
- bash ../.travis/codepush.sh
