export const LOGIN_SUCCESS = "login success"
export const LOGIN_ERROR = "login error"
export const DRAWER_OPEN = "drawer open"
export const DRAWER_CLOSE = "drawer close"
export const DRAWER_TOGGLE = "drawer toggle"
